stages:
  - test

variables:
  MAVEN_OPTS: >-
    -Dhttps.protocols=TLSv1.2
    -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
    -Dorg.slf4j.simpleLogger.showDateTime=true
    -Djava.awt.headless=true

cache:
  paths:
    - .m2/repository

Integration Tests:
  stage: test
  image: eclipse-temurin:21-jdk
  before_script:
    - ./prepare.bash
  script:
    - ./mvnw $MAVEN_CLI_OPTS test
