stages:
  - test

variables:
  MAVEN_OPTS: >-
    -Dhttps.protocols=TLSv1.2
    -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
    -Dorg.slf4j.simpleLogger.showDateTime=true
    -Djava.awt.headless=true

cache:
  paths:
    - .m2/repository

Verify:
  stage: test
  image: eclipse-temurin:20-jdk
  before_script:
    - "./prepare.bash"
  script:
    - "mvn $MAVEN_CLI_OPTS verify"
