name: ci

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  job:
    runs-on: ubuntu-latest
    container:
      image: registry.gitlab.com/easbarba/onur-java:0.4.0

    steps:
      - uses: actions/checkout@v3

      - name: Test
        run: ./mvnw --settings ./.mvn/settings.xml clean compile test
